- name: Install Ollama
  community.general.homebrew:
    name: ollama
    state: present
    force_formula: true

- name: Get user home
  user:
    name: "{{ ansible_user }}"
  register: user
  changed_when: false

- name: Ensure ollama home exists
  file:
    path: "{{ user['home'] }}/.ollama"
    state: directory

- name: Install Ollama launchd template
  template:
    src: ollama.plist
    dest: "/Library/LaunchDaemons/ollama.plist"
    mode: 0644
  become: true
  vars:
    ollama_home: "{{ user['home'] }}/.ollama"
    user_name: "{{ user['name'] }}"

- name: Start Ollama
  community.general.launchd:
    name: ollama
    enabled: true
    state: started
  become: true
