# TODO: Doesn't work, I get Apple provenance sandbox application errors
#- name: Create a mounted data volume for Open WebUI's backend
#  containers.podman.podman_volume:
#    state: present
#    name: open-webui-data

- name: Register/start the Open WebUI container
  containers.podman.podman_container:
    name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    state: started
    ports:
      - '8080:8080'  # TODO: make configurable
    env:
      OLLAMA_BASE_URL: 'http://host.containers.internal:11434'  # TODO: Make configurable
      ANONYMIZED_TELEMETRY: 'False'
    label:
      io.containers.autoupdate: registry
    #volumes:
    #  - 'open-webui-data:/app/backend/data:z'
